[build]
  publish = "."
  functions = "netlify/functions"
  command = ""

# (optionnel) si ton site agit comme une SPA et que tu veux Ã©viter les 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
